using System;
using Newtonsoft.Json;

namespace z5.ms.domain.subscription.viewmodel
{ 
    /// <summary>In-App purchases callback request model</summary>
    public class InappSubscriptionCallback
    { 
        /// <summary>
        /// This is the unique identifier for the prepared subscription.
        /// </summary>
        /// <value>This is the unique identifier for the prepared subscription.</value>
        [JsonProperty("subscription_id", Required = Required.Always)]
        public Guid SubscriptionId { get; set; }

        /// <summary>
        /// The store receipt generated by the In-App store base64 encoded.
        /// </summary>
        /// <value>The store receipt generated by the In-App store base64 encoded.</value>
        [JsonProperty("receipt", Required = Required.Always)]
        public string Receipt { get; set; }
    }

    /// <summary>In-App purchases callback request model</summary>
    public class InappPurchaseCallback
    {
        /// <summary>
        /// This is the unique identifier for the prepared purchase.
        /// </summary>
        /// <value>This is the unique identifier for the prepared purchase.</value>
        [JsonProperty("purchase_id", Required = Required.Always)]
        public Guid PurchaseId { get; set; }

        /// <summary>
        /// The store receipt generated by the In-App store base64 encoded.
        /// </summary>
        /// <value>The store receipt generated by the In-App store base64 encoded.</value>
        [JsonProperty("receipt", Required = Required.Always)]
        public string Receipt { get; set; }
    }
}
